name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        build_type: [Debug, Release]

    name: "${{matrix.build_type}}"

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: |
          cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: make -j -C build

      - name: Run tests
        run: make -j -C build test